- name: Create /etc/containerd/config.toml file
  file:
    state: touch
    path: /etc/containerd/config.toml

- name: Generate containerd config using containerd config default
  shell: |
    containerd config default | sed 's/SystemdCgroup = false/SystemdCgroup = true/' > /etc/containerd/config.toml

- name: Restart containerd
  service:
    name: containerd
    state: restarted

- name: Forwarding IPv4
  template: 
    src: ../files/forwarding_ipv4.j2 
    dest: /etc/modules-load.d/k8s.conf

- name: modprobe
  shell: |
    modprobe overlay
    modprobe br_netfilter

- name: Set up sysctl params
  template: 
    src: ../files/sysctl_params.j2 
    dest: /etc/sysctl.d/k8s.conf

- name: Apply sysctl params without reboot
  shell: |
    sysctl --system
