---
- name: Install kubeadm, kubelet, kubectl
  include_tasks: install_kubeadm_kubelet_kubectl.yml

- name: Install containerd runtime
  include_tasks: install_container_runtime.yml

- name: Configure Cgroup driver
  include_tasks: configure_cgroup_driver.yml

- name: Create cluster with Kubeadm
  include_tasks: create_cluster_kubeadm.yml

- name: Apply network plugin
  include_tasks: apply_plugin.yml