#Download prometheus binary tar file
- name: Download prometheus binary tar file
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/{{ prometheus_dir }}.tar.gz"
    dest: /home/ubuntu
  when: inventory_hostname in groups['control_plane']

- name: Extract the file
  ansible.builtin.unarchive:
    src: /home/ubuntu/{{ prometheus_dir }}.tar.gz
    dest: /home/ubuntu
    remote_src: yes
  when: inventory_hostname in groups['control_plane']

#- name: Copy prometheus binary file and CLI to /usr/local/bin/
#  command: >
#    mv /home/ubuntu/{{ prometheus_dir }}/prometheus /usr/local/bin
#    mv /home/ubuntu/{{ prometheus_dir }}/promtool /usr/local/bin
#  when: inventory_hostname in groups['control_plane']

- name: Move prometheus binaries
  ansible.builtin.copy:
    src: /home/ubuntu/{{ prometheus_dir }}/prometheus
    dest: /usr/local/bin/prometheus
    remote_src: yes
    mode: '0755'
  when:
    - inventory_hostname in groups['control_plane']

- name: Move promtool binary
  ansible.builtin.copy:
    src: /home/ubuntu/{{ prometheus_dir }}/promtool
    dest: /usr/local/bin/promtool
    remote_src: yes
    mode: '0755'
  when:
    - inventory_hostname in groups['control_plane']

- name: Create directory for prometheus
  ansible.builtin.file:
    state: directory
    path: /etc/prometheus
  when: inventory_hostname in groups['control_plane']
  
- name: Move prometheus config file to /etc/prometheus
  command: >
    mv /home/ubuntu/{{ prometheus_dir }}/prometheus.yml /etc/prometheus
  when: inventory_hostname in groups['control_plane']

- name: Create data directory for prometheus
  ansible.builtin.file:
    state: directory
    path: /var/lib/prometheus
    owner: ubuntu
    group: ubuntu
  when: inventory_hostname in groups['control_plane']

- name: Create prometheus.service in systemd
  ansible.builtin.template:
    src: ../files/prometheus.service
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
  when: inventory_hostname in groups['control_plane']

- name: Start and enable prometheus service
  ansible.builtin.systemd_service:
    name: prometheus
    state: started
    enabled: true
    daemon_reload: true
  when: inventory_hostname in groups['control_plane']
